### ISSUE TITLE
ImportError: cannot import name 'AsyncIOEventEmitter' from 'pyee'

### ISSUE THREAD

**Issue by oku32** [isaackogan/Grindr#1]
I'm not well-versed with Python, but I get the following error when trying to import `Grindr`:

```console
Traceback (most recent call last):
  File "/Users/oku/grindr/main.py", line 1, in <module>
    from Grindr import GrindrClient
  File "/Users/oku/grindr/.venv/lib/python3.12/site-packages/Grindr/__init__.py", line 1, in <module>
    from .client.client import GrindrClient
  File "/Users/oku/grindr/.venv/lib/python3.12/site-packages/Grindr/client/client.py", line 14, in <module>
    from Grindr.client.emitter import GrindrEmitter
  File "/Users/oku/grindr/.venv/lib/python3.12/site-packages/Grindr/client/emitter.py", line 3, in <module>
    from pyee import AsyncIOEventEmitter
ImportError: cannot import name 'AsyncIOEventEmitter' from 'pyee' (/Users/oku/grindr/.venv/lib/python3.12/site-packages/pyee/__init__.py)
```

1. `mkdir grindr && cd grindr`
2. `uv virtualenv`
3. `source .venv/bin/activate.fish`
4. `uv pip install Grindr`
5. `hx main.py`
6. Paste the example in **Getting Started** with my own details and execute the file with `python main.py`

Am I doing something horribly wrong here?

**Comment by niewiemczego** [comment]
Go to Grindr -> client -> emitter.py and change the import to look like this `from pyee.asyncio import AsyncIOEventEmitter`

**Comment by isaackogan** [comment]
my bad
